#!/bin/sh

MY_CONFIG="$HOME/csgo/condifgs"
CSGO="$HOME/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/csgo/cfg"

ln -s -f "$MY_CONFIG/autoexec.cfg" "$CSGO"
ln -s -f "$MY_CONFIG/fallen.cfg" "$CSGO"
ln -s -f "$MY_CONFIG/yuri.cfg" "$CSGO"
ln -s -f "$MY_CONFIG/aliases.cfg" "$CSGO"
ln -s -f "$MY_CONFIG/help.cfg" "$CSGO"
ln -s -f "$MY_CONFIG/crosshair.cfg" "$CSGO"
ln -s -f "$MY_CONFIG/crosshair_dot.cfg" "$CSGO"
ln -s -f "$MY_CONFIG/keys.cfg" "$CSGO"
ln -s -f "$MY_CONFIG/CSGO-Bot-Rush" "$CSGO"
